name: Deployment

on:
  push:
    branches: [hexo-dev] # only push events on source branch trigger deployment

jobs:
  hexo-deployment:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.2'

    - name: Install dependencies & Generate static files
      run: |
        node -v
        npm i -g hexo-cli
        npm i
        hexo clean
        hexo g
    - name: Deploy to Github Pages
      env:
        GIT_NAME: TonyMistark
        REPO: TonyMistark/tonymistark.github.io.git
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd ./public && git init
        git status
        git checkout -b hexo
        git add .
        git status
        git config --global user.name $GIT_NAME
        git config --global user.email $GIT_EMAIL
        git add .
        git commit -m "Site deployed by GitHub Actions"
        git add .
        git commit -m "Site deployed by GitHub Actions"
        echo "finishe commit"
        git remote add origin "https://$GH_TOKEN@$REPO" 
        git push origin hexo -f --quiet